import type { Country } from "@/lib/constants/program";

/**
 * Provider-agnostic payment contract.
 *
 * Two rails ship: pawaPay for mobile money (Cameroun, Kenya, Ghana) and
 * Stripe for cards (all six countries — mandatory for Morocco, Egypt and
 * South Africa, which pawaPay does not cover). Flutterwave is pre-declared as
 * a third `PaymentProviderId` so adding it later, if the account is granted,
 * is a registry entry rather than a refactor.
 */

export type PaymentProviderId =
  | "pawapay"
  | "stripe"
  | "paiementpro"
  | "flutterwave";
export type PaymentMethod = "mobile_money" | "card" | "paypal";

export type PaymentStatus =
  | "en_attente"
  | "en_cours"
  | "paye"
  | "echoue"
  | "annule"
  | "rembourse";

export interface Money {
  amountUsd: number;
  amountLocal: number;
  currency: string;
  fxRate: number;
  fxSource: string;
}

export interface CheckoutInput {
  candidatureId: string;
  country: Country;
  /** Which of its channels a multi-channel provider (Paiement Pro) opens. */
  method: PaymentMethod;
  money: Money;
  /**
   * Reference the caller already persisted, from `newReference()`. Providers
   * that mint their own ignore it.
   */
  reference?: string;
  /**
   * Amount as a string, already shaped to the chosen rail's constraints
   * (decimal places, wallet limits). Overrides `money.amountLocal` when set —
   * `money` stays the record of what the candidate was shown and charged.
   */
  amountOverride?: string;
  /** Applicant's phone in E.164 — required by mobile money, ignored by card. */
  phone?: string;
  /**
   * Mobile money operator id, e.g. "MTN_MOMO_CMR". Required by pawaPay v2,
   * which carries the provider inside the deposit payload rather than
   * inferring it from the phone number. Ignored by card providers.
   */
  operator?: string;
  email: string;
  /**
   * Name and phone as given in Phase 1. Some hosted gateways require the payer's
   * identity in the initiation payload rather than collecting it themselves —
   * Paiement Pro rejects an initiation without them.
   */
  customer?: {
    firstName: string;
    lastName: string;
    phone: string;
  };
  locale: string;
  /** Where the provider returns the payer after a hosted flow. */
  returnUrl: string;
  /** Server-to-server callback URL, for gateways configured per payment
   *  rather than per account. */
  notificationUrl?: string;
  description: string;
}

export interface CheckoutResult {
  providerRef: string;
  /**
   * Hosted page to send the payer to. Absent for mobile money, where the
   * prompt is pushed to the handset and there is nowhere to navigate — the
   * UI polls instead.
   */
  redirectUrl?: string;
  /** True when settlement happens out of band and must be polled/awaited. */
  asynchronous: boolean;
}

/**
 * What a settlement rests on. Written onto the payment, because "paid" from a
 * signed callback and "paid" because an unverifiable callback said so are not
 * the same claim, and only the second needs a human to check it.
 */
export type SettlementSource =
  | "provider_signature"
  | "gateway_status"
  | "callback_unverified"
  | "manual";

export interface WebhookEvent {
  /** Provider's event id. The idempotency key — must be stable across retries. */
  eventId: string;
  eventType: string;
  providerRef: string;
  status: PaymentStatus;
  failureReason?: string;
  /** Set when this event settles a payment. Defaults to a signed callback. */
  settlementSource?: SettlementSource;
  raw: unknown;
}

export interface RefundResult {
  refunded: boolean;
  providerRefundRef?: string;
  reason?: string;
}

export interface PaymentProvider {
  readonly id: PaymentProviderId;

  /** Can this provider take this method in this country? */
  supports(country: Country, method: PaymentMethod): boolean;

  /**
   * The only currency this provider's hosted page (card, PayPal) can charge
   * in, when it is not USD. The fee is converted into it before checkout.
   * Absent means USD.
   */
  readonly chargeCurrency?: string;

  /**
   * A provider reference generated by US, before anything is initiated.
   *
   * pawaPay requires this: the `depositId` must be stored before the deposit
   * is initiated, so that a timeout or a crash still leaves a reference we can
   * reconcile against instead of a possible charge with no record of it.
   *
   * Absent for providers that mint their own reference during checkout (a
   * Stripe session id cannot be known in advance).
   */
  newReference?(): string;

  createCheckout(input: CheckoutInput): Promise<CheckoutResult>;

  /**
   * Verify and parse an inbound webhook.
   *
   * Takes the RAW body string, never a parsed object: every provider signs
   * the exact bytes it sent, and `JSON.parse` followed by `JSON.stringify`
   * will not reproduce them. Returns null when the signature fails — the
   * route must then reject without touching any payment.
   *
   * The `Request` is passed whole rather than just its headers because
   * RFC-9421 signatures (pawaPay) cover the method and path as well as the
   * body digest.
   */
  verifyWebhook(rawBody: string, request: Request): Promise<WebhookEvent | null>;

  /**
   * Second opinion on a callback that carried no verifiable signature.
   *
   * Set only by providers that cannot sign. The webhook route looks the
   * payment up first and hands over the figures we recorded, so the decision
   * can be made against them — a signature's job, done with whatever evidence
   * the provider actually offers. Returning `callback_unverified` says: act on
   * it, but it has not been proven, so put it in front of an administrator.
   *
   * Without this, such an event is applied as-is, which no unsigned provider
   * should get.
   */
  confirmEvent?(
    event: WebhookEvent,
    expected: { amountLocal: number; amountUsd: number },
  ): Promise<{
    status: PaymentStatus;
    failureReason?: string;
    settlementSource: SettlementSource;
  }>;

  /**
   * Authoritative status straight from the provider.
   *
   * The fallback whenever a webhook is late or lost, and the only way an
   * asynchronous mobile-money collection resolves in the UI. Never trust the
   * browser's return from a hosted page for this.
   *
   * `expected` is what we recorded at checkout, in both currencies. Providers
   * that cannot sign their callbacks compare it against what the gateway
   * reports and refuse to settle on a mismatch — for them it is the substitute
   * for a signature. Both figures are passed because a gateway that converts
   * (Paiement Pro charges in USD what we quoted in XOF) may answer in either.
   * Providers with real signatures ignore it.
   */
  getStatus(
    providerRef: string,
    expected?: { amountLocal: number; amountUsd: number },
  ): Promise<{
    status: PaymentStatus;
    failureReason?: string;
  }>;

  refund(providerRef: string, amountUsd: number): Promise<RefundResult>;
}

/** Thrown when a provider is misconfigured — surfaces as a 500, never a silent skip. */
export class PaymentConfigError extends Error {}
